POST http://localhost:8000/handyman/
Content-Type: application/json

{
    "name": "J",
    "profession": "mason",
    "city": "Benin",
    "tel": "09099009978"
}

###
PUT http://localhost:8000/handyman/
Content-Type: application/json

{
    "name": "Joshua",
    "profession": "mason",
    "city": "Benin",
    "tel": "09099009978"
}

###
GET http://localhost:8000/handyman/

###
GET http://localhost:8000/handyman/6557c6fda6fc8fdae8a23c72

####
GET http://localhost:8000/handyman/profession/{"profession": "mason"}